services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 16000:8080

  db:
    image: docker.io/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password

  pgadmin:
    image: docker.io/dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
